apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-agent-lls

resources:
  - ../../base

configMapGenerator:
  - name: llama-stack-config
    files:
      - run.yaml

patches:
  - path: llamastack-patch.yaml

configurations:
  - cm-name-replacement.yaml
